"use strict";

/**
 * Cultural knowledge library seed for Masters of Yesterday.
 * Only entries with reviewStatus === "approved" are used for automatic prep.
 * Extensible: append objects; do not invent facts at generation time.
 */

/** @type {Array<object>} */
const CULTURAL_CATALOGUE = [
  // —— Indigenous Australia ——
  {
    id: "au-boonwurrung",
    countryStream: "indigenous-australia",
    subject: "Boonwurrung people",
    subjectType: "Indigenous nation",
    region: "Kulin Nation — Melbourne and Mornington Peninsula",
    shortSummary:
      "Boonwurrung people are original custodians of coastal lands around Melbourne and the Mornington Peninsula within the Kulin Nation.",
    verifiedFacts: [
      "Belong to the Kulin Nation as original custodians of the Melbourne and Mornington Peninsula area.",
      "Known for deep connection to coastal land and sea, including seasonal movement for resources.",
      "Shellfish gathering and fishing shaped local diets and trade.",
    ],
    modernSignificance:
      "These traditions remain vital today, preserving cultural identity and environmental care.",
    keywords: ["Boonwurrung", "Kulin", "coastal", "Melbourne"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Origins", "#Boonwurrung"],
    sourceReferences: [
      { title: "Editorial style reference — Boonwurrung (OROK)", note: "style reference, not automatic verification" },
    ],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "coastal gathering and fishing practice",
    imageEnvironment: "Victorian coastal estuary and shoreline",
    imageObjects: ["woven baskets", "shells", "shallow water"],
    prohibitedVisualElements: ["fake ceremony", "generic tribal costume", "mixed Pacific cultures"],
  },
  {
    id: "au-wurundjeri",
    countryStream: "indigenous-australia",
    subject: "Wurundjeri Woi-wurrung people",
    subjectType: "Indigenous nation",
    region: "Kulin Nation — Yarra River / Birrarung country",
    shortSummary:
      "Wurundjeri Woi-wurrung people are custodians of lands along the Yarra River (Birrarung) in central Victoria.",
    verifiedFacts: [
      "Part of the Kulin Nation with custodianship connected to the Yarra River (Birrarung).",
      "Country includes river corridors, grasslands and foothills around present-day Melbourne.",
      "Language, kinship and land care practices continue through community leadership today.",
    ],
    modernSignificance:
      "Wurundjeri knowledge still guides cultural continuity and care for river country.",
    keywords: ["Wurundjeri", "Woi-wurrung", "Birrarung", "Yarra"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Origins", "#Wurundjeri"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "riverside teaching and land care",
    imageEnvironment: "Yarra / Birrarung riverbank woodland",
    imageObjects: ["river water", "native plants", "walking tracks"],
    prohibitedVisualElements: ["fake ceremony", "generic desert imagery", "mixed cultures"],
  },
  {
    id: "au-yolngu",
    countryStream: "indigenous-australia",
    subject: "Yolŋu peoples",
    subjectType: "people",
    region: "North-east Arnhem Land, Northern Territory",
    shortSummary:
      "Yolŋu peoples of north-east Arnhem Land maintain distinct clan estates, languages and sea–land knowledge.",
    verifiedFacts: [
      "Live in north-east Arnhem Land with interconnected clan estates.",
      "Sea and land knowledge guide hunting, fishing and seasonal movement.",
      "Yolŋu languages and law remain central to identity and community life.",
    ],
    modernSignificance:
      "Yolŋu cultural authority continues to shape education, art and care for country.",
    keywords: ["Yolŋu", "Arnhem Land", "clan"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Origins", "#Yolngu"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "coastal fishing and shoreline knowledge",
    imageEnvironment: "Arnhem Land tropical coastline",
    imageObjects: ["dugout or shoreline gear", "tidal flats"],
    prohibitedVisualElements: ["sacred ceremony detail", "costume staging", "mixed cultures"],
  },
  {
    id: "au-noongar",
    countryStream: "indigenous-australia",
    subject: "Noongar people",
    subjectType: "Indigenous nation",
    region: "South-west Western Australia",
    shortSummary:
      "Noongar people are the Traditional Owners of a large region of south-west Western Australia.",
    verifiedFacts: [
      "Traditional Owners across south-west Western Australia.",
      "Knowledge systems include six seasons guiding movement and resource use.",
      "Language revitalisation and community leadership continue across Noongar country.",
    ],
    modernSignificance:
      "Noongar language and seasonal knowledge remain active in community life and education.",
    keywords: ["Noongar", "southwest WA", "six seasons"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Origins", "#Noongar"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "seasonal gathering in bushland",
    imageEnvironment: "south-west WA bush and wetland edges",
    imageObjects: ["native vegetation", "gathering baskets"],
    prohibitedVisualElements: ["generic outback stereotype", "fake ceremony"],
  },
  {
    id: "au-arrernte",
    countryStream: "indigenous-australia",
    subject: "Arrernte people",
    subjectType: "Indigenous nation",
    region: "Central Australia — Mparntwe / Alice Springs region",
    shortSummary:
      "Arrernte people are custodians of country around Mparntwe (Alice Springs) in Central Australia.",
    verifiedFacts: [
      "Custodians of country around Mparntwe (Alice Springs) in Central Australia.",
      "Language and kinship systems remain foundational to community life.",
      "Stories of place connect people to ranges, waterholes and travel routes.",
    ],
    modernSignificance:
      "Arrernte language and place knowledge continue to guide cultural continuity in Central Australia.",
    keywords: ["Arrernte", "Mparntwe", "Central Australia"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Origins", "#Arrernte"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "teaching beside familiar country landmarks",
    imageEnvironment: "Central Australian ranges and open scrub",
    imageObjects: ["red earth paths", "native scrub"],
    prohibitedVisualElements: ["sacred site intrusion", "tourist stereotype staging"],
  },
  {
    id: "au-kaurna",
    countryStream: "indigenous-australia",
    subject: "Kaurna people",
    subjectType: "Indigenous nation",
    region: "Adelaide Plains, South Australia",
    shortSummary:
      "Kaurna people are Traditional Owners of the Adelaide Plains region of South Australia.",
    verifiedFacts: [
      "Traditional Owners of the Adelaide Plains.",
      "Language revitalisation has returned Kaurna names and greetings into public life.",
      "Coastal and plains country knowledge informs contemporary cultural practice.",
    ],
    modernSignificance:
      "Kaurna language revival shows living culture continuing on plains country.",
    keywords: ["Kaurna", "Adelaide Plains"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Origins", "#Kaurna"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "language teaching and community greeting practice",
    imageEnvironment: "Adelaide Plains parkland and coastal edge",
    imageObjects: ["open grass plains", "coastal light"],
    prohibitedVisualElements: ["fake ceremony", "mixed cultures"],
  },
  {
    id: "au-palawa",
    countryStream: "indigenous-australia",
    subject: "Palawa people",
    subjectType: "Indigenous nation",
    region: "lutruwita / Tasmania",
    shortSummary:
      "Palawa people are the Aboriginal people of lutruwita (Tasmania) with enduring community identity.",
    verifiedFacts: [
      "Aboriginal people of lutruwita (Tasmania).",
      "Community continuity includes language work, family networks and cultural advocacy.",
      "Connection to island and coastal country remains central to identity.",
    ],
    modernSignificance:
      "Palawa communities continue cultural recovery and public recognition across Tasmania.",
    keywords: ["Palawa", "lutruwita", "Tasmania"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Origins", "#Palawa"],
    sourceReferences: [],
    confidence: "medium",
    reviewStatus: "approved",
    imageBehaviourSignal: "coastal family gathering on island country",
    imageEnvironment: "Tasmanian shoreline and scrub",
    imageObjects: ["coastal rocks", "native scrub"],
    prohibitedVisualElements: ["extinction myths imagery", "costume staging"],
  },
  {
    id: "au-yuin",
    countryStream: "indigenous-australia",
    subject: "Yuin people",
    subjectType: "Indigenous nation",
    region: "South coast of New South Wales",
    shortSummary:
      "Yuin people are Traditional Owners along the south coast of New South Wales.",
    verifiedFacts: [
      "Traditional Owners of south-coast NSW country.",
      "Sea and forest knowledge support fishing, gathering and travel along the coast.",
      "Community leadership continues cultural education and land–sea care.",
    ],
    modernSignificance:
      "Yuin cultural practice continues along the south coast through community teaching and care for country.",
    keywords: ["Yuin", "NSW south coast"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Origins", "#Yuin"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "coastal fishing and shoreline walking",
    imageEnvironment: "NSW south-coast beaches and bush behind dunes",
    imageObjects: ["fishing gear", "shoreline"],
    prohibitedVisualElements: ["generic tribal collage", "mixed cultures"],
  },
  {
    id: "au-wiradjuri",
    countryStream: "indigenous-australia",
    subject: "Wiradjuri people",
    subjectType: "Indigenous nation",
    region: "Central New South Wales",
    shortSummary:
      "Wiradjuri people are one of the largest Aboriginal nations in central New South Wales.",
    verifiedFacts: [
      "One of the largest Aboriginal nations in central New South Wales.",
      "Country includes river systems and inland plains.",
      "Language revitalisation and community programs continue across Wiradjuri country.",
    ],
    modernSignificance:
      "Wiradjuri language and kinship continue to strengthen identity across inland NSW.",
    keywords: ["Wiradjuri", "central NSW"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Origins", "#Wiradjuri"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "riverside teaching and family travel",
    imageEnvironment: "inland river plains of central NSW",
    imageObjects: ["riverbanks", "native trees"],
    prohibitedVisualElements: ["fake ceremony", "desert-only stereotype"],
  },

  // —— Cook Islands ——
  {
    id: "ck-rarotonga",
    countryStream: "cook-islands",
    subject: "Rarotonga",
    subjectType: "island community",
    region: "Southern Cook Islands",
    shortSummary:
      "Rarotonga is the most populous island of the Cook Islands and a centre of cultural and political life.",
    verifiedFacts: [
      "Most populous island of the Cook Islands.",
      "Home to Avarua, the national capital, and major marae and community networks.",
      "Agriculture, lagoon fishing and family land ties shape daily life.",
    ],
    modernSignificance:
      "Rarotonga remains a hub for Cook Islands language, family gatherings and cultural continuity.",
    keywords: ["Rarotonga", "Avarua", "Cook Islands"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#CookIslands", "#Rarotonga"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "lagoon fishing and coastal food preparation",
    imageEnvironment: "Rarotonga lagoon and mountain backdrop",
    imageObjects: ["outrigger canoe", "coconuts", "reef edge"],
    prohibitedVisualElements: ["fake tourist luau", "mixed Melanesian costume stereotypes"],
  },
  {
    id: "ck-aitutaki",
    countryStream: "cook-islands",
    subject: "Aitutaki",
    subjectType: "island community",
    region: "Southern Cook Islands",
    shortSummary:
      "Aitutaki is known for its large lagoon and strong family links across the Cook Islands diaspora.",
    verifiedFacts: [
      "Island in the southern Cook Islands famous for its expansive lagoon.",
      "Communities maintain fishing, planting and family connections across islands and to Aotearoa.",
      "Local identity is tied to lagoon livelihoods and village life.",
    ],
    modernSignificance:
      "Aitutaki families continue language and island practice at home and abroad.",
    keywords: ["Aitutaki", "lagoon"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#CookIslands", "#Aitutaki"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "lagoon travel and fishing",
    imageEnvironment: "Aitutaki motu and turquoise lagoon",
    imageObjects: ["small boat", "net", "palm shade"],
    prohibitedVisualElements: ["generic tropical stock collage", "fake ceremony"],
  },
  {
    id: "ck-atiu",
    countryStream: "cook-islands",
    subject: "Atiu",
    subjectType: "island community",
    region: "Southern Cook Islands",
    shortSummary:
      "Atiu (Enua Manu) is a raised coral island with strong traditional food and cave-country knowledge.",
    verifiedFacts: [
      "Raised coral island in the southern Cook Islands, also known as Enua Manu.",
      "Communities are known for coffee growing, hunting and cave environments inland from the coast.",
      "Village life keeps land and food practices central.",
    ],
    modernSignificance:
      "Atiu practices of food, land and community still shape island identity today.",
    keywords: ["Atiu", "Enua Manu"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#CookIslands", "#Atiu"],
    sourceReferences: [],
    confidence: "medium",
    reviewStatus: "approved",
    imageBehaviourSignal: "inland path walking and food preparation",
    imageEnvironment: "Atiu raised island bush and coastal cliffs",
    imageObjects: ["coffee plants", "woven baskets"],
    prohibitedVisualElements: ["cave sacred intrusion", "fantasy lighting"],
  },
  {
    id: "ck-mangaia",
    countryStream: "cook-islands",
    subject: "Mangaia",
    subjectType: "island community",
    region: "Southern Cook Islands",
    shortSummary:
      "Mangaia is the most southerly of the Cook Islands, known for makatea limestone and deep island history.",
    verifiedFacts: [
      "Most southerly of the major Cook Islands.",
      "Distinct raised limestone (makatea) surrounds fertile inland lands.",
      "Strong oral histories and village structures continue community life.",
    ],
    modernSignificance:
      "Mangaia’s landscapes and community knowledge remain central to island identity.",
    keywords: ["Mangaia", "makatea"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#CookIslands", "#Mangaia"],
    sourceReferences: [],
    confidence: "medium",
    reviewStatus: "approved",
    imageBehaviourSignal: "farming on inland terraces",
    imageEnvironment: "Mangaia makatea rim and green interior",
    imageObjects: ["planting tools", "limestone cliffs at distance"],
    prohibitedVisualElements: ["fake ceremony", "mixed cultures"],
  },
  {
    id: "ck-mauke",
    countryStream: "cook-islands",
    subject: "Mauke",
    subjectType: "island community",
    region: "Southern Cook Islands",
    shortSummary:
      "Mauke is a southern Cook Islands community known for fertile soils and close village networks.",
    verifiedFacts: [
      "Southern Cook Islands island with fertile growing land.",
      "Village life centres on planting, fishing and family obligations.",
      "Connections to neighbouring islands remain important for travel and kinship.",
    ],
    modernSignificance:
      "Mauke families keep planting and kinship practices alive across generations.",
    keywords: ["Mauke"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#CookIslands", "#Mauke"],
    sourceReferences: [],
    confidence: "medium",
    reviewStatus: "approved",
    imageBehaviourSignal: "garden planting and food sharing",
    imageEnvironment: "Mauke village gardens and coastal fringe",
    imageObjects: ["taro or garden beds", "hand tools"],
    prohibitedVisualElements: ["tourist cliché staging"],
  },
  {
    id: "ck-mitiaro",
    countryStream: "cook-islands",
    subject: "Mitiaro",
    subjectType: "island community",
    region: "Southern Cook Islands",
    shortSummary:
      "Mitiaro is a small southern Cook Island with freshwater lakes and strong communal living patterns.",
    verifiedFacts: [
      "Small southern Cook Island featuring inland freshwater lakes.",
      "Communities rely on planting, fishing and shared village work.",
      "Limited population keeps kinship and mutual support highly visible.",
    ],
    modernSignificance:
      "Mitiaro’s communal habits continue to model close island interdependence.",
    keywords: ["Mitiaro"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#CookIslands", "#Mitiaro"],
    sourceReferences: [],
    confidence: "medium",
    reviewStatus: "approved",
    imageBehaviourSignal: "shared village work near freshwater lakes",
    imageEnvironment: "Mitiaro lakes and low coastal scrub",
    imageObjects: ["lake edge", "woven mats"],
    prohibitedVisualElements: ["fake ceremony"],
  },
  {
    id: "ck-manihiki",
    countryStream: "cook-islands",
    subject: "Manihiki",
    subjectType: "island community",
    region: "Northern Cook Islands",
    shortSummary:
      "Manihiki is a northern Cook Islands atoll known for pearl farming and lagoon livelihoods.",
    verifiedFacts: [
      "Northern Cook Islands atoll.",
      "Pearl farming and lagoon work are major livelihoods.",
      "Communities live around the lagoon with strong seafaring skills.",
    ],
    modernSignificance:
      "Manihiki lagoon work and family enterprise continue to sustain island life.",
    keywords: ["Manihiki", "pearls", "atoll"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#CookIslands", "#Manihiki"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "lagoon work and pearl farming activity",
    imageEnvironment: "Manihiki atoll lagoon",
    imageObjects: ["small boats", "pearl farm lines"],
    prohibitedVisualElements: ["luxury fantasy staging", "mixed cultures"],
  },
  {
    id: "ck-tongareva",
    countryStream: "cook-islands",
    subject: "Tongareva",
    subjectType: "island community",
    region: "Northern Cook Islands (Penrhyn)",
    shortSummary:
      "Tongareva (Penrhyn) is a large northern atoll with deep seafaring and lagoon traditions.",
    verifiedFacts: [
      "Also known as Penrhyn; a large northern Cook Islands atoll.",
      "Communities maintain fishing, weaving and seafaring skills.",
      "Remoteness shapes self-reliance and strong local identity.",
    ],
    modernSignificance:
      "Tongareva skills of sea and craft continue through family practice.",
    keywords: ["Tongareva", "Penrhyn"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#CookIslands", "#Tongareva"],
    sourceReferences: [],
    confidence: "medium",
    reviewStatus: "approved",
    imageBehaviourSignal: "weaving and lagoon fishing",
    imageEnvironment: "northern atoll shoreline",
    imageObjects: ["woven hats or mats", "fishing line"],
    prohibitedVisualElements: ["fake ceremony", "generic Polynesia mashup"],
  },
  {
    id: "ck-pukapuka",
    countryStream: "cook-islands",
    subject: "Pukapuka",
    subjectType: "island community",
    region: "Northern Cook Islands",
    shortSummary:
      "Pukapuka is a northern Cook Islands atoll with a distinct language variety and communal food systems.",
    verifiedFacts: [
      "Northern Cook Islands atoll with a distinct local language variety.",
      "Communal food sharing and village organisation remain important.",
      "Strong diaspora links connect Pukapuka to Aotearoa and beyond.",
    ],
    modernSignificance:
      "Pukapuka language and communal habits continue across the islands and diaspora.",
    keywords: ["Pukapuka"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#CookIslands", "#Pukapuka"],
    sourceReferences: [],
    confidence: "medium",
    reviewStatus: "approved",
    imageBehaviourSignal: "communal food preparation",
    imageEnvironment: "Pukapuka village and lagoon edge",
    imageObjects: ["shared food tables", "coconut"],
    prohibitedVisualElements: ["fake ceremony"],
  },

  // —— Aotearoa New Zealand ——
  {
    id: "nz-mataatua",
    countryStream: "aotearoa-new-zealand",
    subject: "Mataatua waka traditions",
    subjectType: "waka tradition",
    region: "Bay of Plenty — Whakatāne",
    shortSummary:
      "Mataatua was a significant ocean-going waka linked to early Māori settlement in the Bay of Plenty.",
    verifiedFacts: [
      "Large ocean-going waka associated with early Māori settlement traditions.",
      "Traditions recall leadership of the tohunga Toroa and landfall at Whakatāne in the Bay of Plenty.",
      "The waka is linked with bringing kūmara to the region in oral tradition.",
    ],
    modernSignificance:
      "Mataatua’s legacy continues to strengthen iwi identity and cultural revival.",
    keywords: ["Mataatua", "Whakatāne", "waka"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Mataatua", "#Aotearoa"],
    sourceReferences: [
      { title: "Editorial style reference — Mataatua (OROK)", note: "style reference" },
    ],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "coastal navigation and landing remembrance",
    imageEnvironment: "Bay of Plenty coastline near Whakatāne",
    imageObjects: ["waka at shore distance", "kūmara garden"],
    prohibitedVisualElements: ["fantasy battle scenes", "mixed Pacific costumes"],
  },
  {
    id: "nz-ngapuhi",
    countryStream: "aotearoa-new-zealand",
    subject: "Ngāpuhi",
    subjectType: "iwi",
    region: "Northland / Te Tai Tokerau",
    shortSummary:
      "Ngāpuhi is a major iwi of Te Tai Tokerau (Northland) with extensive hapū networks.",
    verifiedFacts: [
      "Major iwi of Te Tai Tokerau (Northland).",
      "Made up of many hapū with deep connections to harbours, forests and coastal routes.",
      "Language, marae and hapū leadership remain central today.",
    ],
    modernSignificance:
      "Ngāpuhi hapū continue to lead language, marae life and regional identity in the north.",
    keywords: ["Ngāpuhi", "Tai Tokerau"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Aotearoa", "#Ngapuhi"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "marae gathering and coastal travel",
    imageEnvironment: "Northland harbour and bush",
    imageObjects: ["waka at distance", "marae exterior without sacred interior detail"],
    prohibitedVisualElements: ["sacred interior filming", "fake tattoo close-ups as costume"],
  },
  {
    id: "nz-ngati-porou",
    countryStream: "aotearoa-new-zealand",
    subject: "Ngāti Porou",
    subjectType: "iwi",
    region: "East Coast — Te Tairāwhiti",
    shortSummary:
      "Ngāti Porou is an iwi of Te Tairāwhiti on the East Coast of Te Ika-a-Māui.",
    verifiedFacts: [
      "Iwi of the East Coast (Te Tairāwhiti).",
      "Strong associations with maunga, coastal settlements and te reo revitalisation.",
      "Community leadership continues across marae and education.",
    ],
    modernSignificance:
      "Ngāti Porou continues to renew language and coastal identity on the East Coast.",
    keywords: ["Ngāti Porou", "Tairāwhiti"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Aotearoa", "#NgatiPorou"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "coastal teaching and community work",
    imageEnvironment: "East Coast hills meeting the sea",
    imageObjects: ["coastal road settlements", "native bush"],
    prohibitedVisualElements: ["fake ceremony", "mixed cultures"],
  },
  {
    id: "nz-waikato-tainui",
    countryStream: "aotearoa-new-zealand",
    subject: "Waikato-Tainui",
    subjectType: "iwi",
    region: "Waikato",
    shortSummary:
      "Waikato-Tainui is a major iwi confederation of the Waikato region with Kīngitanga connections.",
    verifiedFacts: [
      "Major iwi grouping of the Waikato region.",
      "Closely associated with the Kīngitanga (Māori King movement) and river country.",
      "Contemporary governance includes tribal development and cultural programmes.",
    ],
    modernSignificance:
      "Waikato-Tainui continues cultural leadership through iwi institutions and river relationships.",
    keywords: ["Waikato", "Tainui", "Kīngitanga"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Aotearoa", "#Waikato"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "river travel and community gathering",
    imageEnvironment: "Waikato river plains",
    imageObjects: ["river craft at distance", "farm and wetland edges"],
    prohibitedVisualElements: ["political caricature", "sacred interior detail"],
  },
  {
    id: "nz-ngai-tahu",
    countryStream: "aotearoa-new-zealand",
    subject: "Ngāi Tahu",
    subjectType: "iwi",
    region: "Te Waipounamu / South Island",
    shortSummary:
      "Ngāi Tahu is the principal iwi of much of Te Waipounamu (the South Island).",
    verifiedFacts: [
      "Principal iwi across much of Te Waipounamu (South Island).",
      "Known for pounamu relationships, mahinga kai and extensive takiwā.",
      "Iwi development includes language, business and environmental initiatives.",
    ],
    modernSignificance:
      "Ngāi Tahu continues to care for mahinga kai and cultural identity across the South Island.",
    keywords: ["Ngāi Tahu", "pounamu", "mahinga kai"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Aotearoa", "#NgaiTahu"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "mahinga kai gathering and river/coast practice",
    imageEnvironment: "South Island braided river or coastal landscape",
    imageObjects: ["fishing or gathering tools", "cold clear water"],
    prohibitedVisualElements: ["pounamu as costume jewellery fantasy", "fake ceremony"],
  },
  {
    id: "nz-te-arawa",
    countryStream: "aotearoa-new-zealand",
    subject: "Te Arawa",
    subjectType: "iwi",
    region: "Rotorua / Bay of Plenty lakes district",
    shortSummary:
      "Te Arawa is an iwi confederation centred on the lakes district around Rotorua.",
    verifiedFacts: [
      "Iwi confederation of the Rotorua lakes district.",
      "Geothermal landscapes and lake resources shape local history and identity.",
      "Arts, carving and hospitality traditions remain highly visible.",
    ],
    modernSignificance:
      "Te Arawa cultural practice continues through marae, arts and lake relationships.",
    keywords: ["Te Arawa", "Rotorua"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Aotearoa", "#TeArawa"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "carving workshop and lakeside community life",
    imageEnvironment: "Rotorua lakes and geothermal landscape at respectful distance",
    imageObjects: ["carving tools", "lake edge"],
    prohibitedVisualElements: ["sacred geothermal misuse", "tourist performance staging as fake ritual"],
  },
  {
    id: "nz-tuhoe",
    countryStream: "aotearoa-new-zealand",
    subject: "Tūhoe",
    subjectType: "iwi",
    region: "Te Urewera",
    shortSummary:
      "Tūhoe are an iwi of Te Urewera with deep relationships to forested mountain country.",
    verifiedFacts: [
      "Iwi of Te Urewera forested mountain country.",
      "Identity is closely tied to the bush, rivers and autonomy of the homeland.",
      "Contemporary settlement arrangements recognise Tūhoe leadership in Te Urewera care.",
    ],
    modernSignificance:
      "Tūhoe continue to lead care for Te Urewera and living cultural practice.",
    keywords: ["Tūhoe", "Te Urewera"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Aotearoa", "#Tuhoe"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "forest travel and teaching on bush tracks",
    imageEnvironment: "Te Urewera native forest",
    imageObjects: ["bush tracks", "river crossings"],
    prohibitedVisualElements: ["militarised stereotypes", "sacred site intrusion"],
  },
  {
    id: "nz-ngati-kahungunu",
    countryStream: "aotearoa-new-zealand",
    subject: "Ngāti Kahungunu",
    subjectType: "iwi",
    region: "Hawke’s Bay / east coast of Te Ika-a-Māui",
    shortSummary:
      "Ngāti Kahungunu is a large iwi along the eastern coast of the North Island, including Hawke’s Bay.",
    verifiedFacts: [
      "Large iwi of the eastern North Island, including Hawke’s Bay.",
      "Coastal and river resources support traditional food economies.",
      "Iwi organisations continue education, health and cultural programmes.",
    ],
    modernSignificance:
      "Ngāti Kahungunu continues coastal identity through marae, food practice and community leadership.",
    keywords: ["Ngāti Kahungunu", "Hawke’s Bay"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Aotearoa", "#NgatiKahungunu"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "coastal fishing and food preparation",
    imageEnvironment: "Hawke’s Bay coastline",
    imageObjects: ["fishing nets", "shoreline"],
    prohibitedVisualElements: ["fake ceremony", "mixed cultures"],
  },

  // —— Peru ——
  {
    id: "pe-achuar",
    countryStream: "peru",
    subject: "Achuar people",
    subjectType: "people",
    region: "Northeastern Peruvian Amazon",
    shortSummary:
      "The Achuar people of the northeastern Peruvian Amazon maintain territory defence and community traditions.",
    verifiedFacts: [
      "Indigenous people of the northeastern Peruvian Amazon.",
      "Community traditions include ceremonial practices connected to health and cultural identity.",
      "Political organisation has helped secure legal recognition of ancestral territories in Peru.",
    ],
    modernSignificance:
      "Achuar leadership continues to protect lands and cultural continuity in the Amazon.",
    keywords: ["Achuar", "Amazon", "Peru"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Culture", "#Achuar"],
    sourceReferences: [
      { title: "Editorial style reference — Achuar (OROK)", note: "style reference" },
    ],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "river travel and community forest livelihood",
    imageEnvironment: "Peruvian Amazon river and forest clearing",
    imageObjects: ["canoe", "forest path"],
    prohibitedVisualElements: [
      "ayahuasca as entertainment spectacle",
      "sacred ceremony close-up",
      "generic tribal collage",
    ],
  },
  {
    id: "pe-quechua",
    countryStream: "peru",
    subject: "Quechua peoples",
    subjectType: "people",
    region: "Andean highlands of Peru",
    shortSummary:
      "Quechua peoples across the Andean highlands maintain language, agriculture and community organisation.",
    verifiedFacts: [
      "Peoples of the Andean highlands with Quechua languages widely spoken in Peru.",
      "Terracing, potato and maize agriculture remain important highland practices.",
      "Community labour traditions (ayni / minka forms) continue in many regions.",
    ],
    modernSignificance:
      "Quechua language and highland farming knowledge remain living Andean strengths.",
    keywords: ["Quechua", "Andes", "terracing"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Culture", "#Quechua"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "terraced farming and family agricultural work",
    imageEnvironment: "Andean terraces and highland village",
    imageObjects: ["potato fields", "woven cloth in daily use"],
    prohibitedVisualElements: ["Inca fantasy mashup", "costume tourism staging"],
  },
  {
    id: "pe-aymara",
    countryStream: "peru",
    subject: "Aymara people",
    subjectType: "people",
    region: "Altiplano around Lake Titicaca (Peru–Bolivia)",
    shortSummary:
      "Aymara people of the altiplano maintain lakeside agriculture, language and community life around Titicaca.",
    verifiedFacts: [
      "Indigenous people of the high altiplano, including Peruvian shores of Lake Titicaca.",
      "Languages and community organisation remain active.",
      "Lakeside agriculture and reed-related crafts are part of regional livelihoods.",
    ],
    modernSignificance:
      "Aymara language and altiplano livelihoods continue around Lake Titicaca.",
    keywords: ["Aymara", "Titicaca", "altiplano"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Culture", "#Aymara"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "lakeside farming and reed craft",
    imageEnvironment: "Lake Titicaca shoreline altiplano",
    imageObjects: ["reed boats at distance", "fields"],
    prohibitedVisualElements: ["fake floating-island stereotype only", "sacred ritual staging"],
  },
  {
    id: "pe-inca",
    countryStream: "peru",
    subject: "Inca civilisation",
    subjectType: "civilisation",
    region: "Andes — historic Tawantinsuyu centred on Cusco",
    shortSummary:
      "The Inca civilisation organised a vast Andean state known as Tawantinsuyu, centred on Cusco.",
    verifiedFacts: [
      "Andean civilisation that organised Tawantinsuyu across western South America.",
      "Known for road networks, administrative centres and high-altitude agriculture.",
      "Quechua language and Andean engineering knowledge outlasted the political empire.",
    ],
    modernSignificance:
      "Inca-era landscapes and knowledge still inform Andean identity and heritage care.",
    keywords: ["Inca", "Tawantinsuyu", "Cusco"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Culture", "#Inca"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "stonework paths and highland travel",
    imageEnvironment: "Andean highland archaeological landscape without fake reconstruction as fact",
    imageObjects: ["stone terraces", "mountain paths"],
    prohibitedVisualElements: ["aliens myths", "fantasy gold cities", "costume emperors"],
  },
  {
    id: "pe-chachapoya",
    countryStream: "peru",
    subject: "Chachapoya culture",
    subjectType: "cultural tradition",
    region: "Cloud forests of northern Peru",
    shortSummary:
      "Chachapoya culture developed in the cloud forests of northern Peru before Inca expansion.",
    verifiedFacts: [
      "Culture of the cloud-forest regions of northern Peru.",
      "Known archaeologically for cliff tombs and settlements such as around Kuélap.",
      "Later interacted with expanding Inca power in the region.",
    ],
    modernSignificance:
      "Chachapoya heritage sites continue to shape northern Peru’s cultural landscape.",
    keywords: ["Chachapoya", "Kuélap", "cloud forest"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Culture", "#Chachapoya"],
    sourceReferences: [],
    confidence: "medium",
    reviewStatus: "approved",
    imageBehaviourSignal: "cloud-forest path travel near stone settlements",
    imageEnvironment: "northern Peru cloud forest ridges",
    imageObjects: ["stone walls at respectful distance", "mist forest"],
    prohibitedVisualElements: ["tomb disturbance imagery", "fantasy warriors"],
  },
  {
    id: "pe-moche",
    countryStream: "peru",
    subject: "Moche civilisation",
    subjectType: "civilisation",
    region: "North coast of Peru",
    shortSummary:
      "The Moche civilisation flourished on Peru’s north coast with irrigation agriculture and fine ceramics.",
    verifiedFacts: [
      "North-coast Peruvian civilisation known for irrigation agriculture.",
      "Produced distinctive ceramics and monumental adobe structures.",
      "Coastal valleys supported dense settlement before later polities.",
    ],
    modernSignificance:
      "Moche archaeological landscapes remain central to understanding Peru’s north coast.",
    keywords: ["Moche", "north coast Peru"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Culture", "#Moche"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "irrigation canal work and coastal valley farming",
    imageEnvironment: "Peruvian north-coast desert valley",
    imageObjects: ["adobe walls at distance", "irrigation channels"],
    prohibitedVisualElements: ["graphic sacrifice sensationalism", "fake ceremony recreation"],
  },
  {
    id: "pe-nazca",
    countryStream: "peru",
    subject: "Nazca culture",
    subjectType: "cultural tradition",
    region: "South coast of Peru",
    shortSummary:
      "Nazca culture of Peru’s south coast is known for geoglyphs, aqueducts and desert valley life.",
    verifiedFacts: [
      "South-coast culture associated with the Nazca geoglyphs and desert valleys.",
      "Developed underground aqueduct systems (puquios) to support agriculture.",
      "Ceramic and textile traditions are well attested archaeologically.",
    ],
    modernSignificance:
      "Nazca heritage draws attention to desert engineering and coastal desert livelihoods.",
    keywords: ["Nazca", "puquios", "geoglyphs"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Culture", "#Nazca"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "desert valley farming near aqueduct openings",
    imageEnvironment: "Nazca desert valley",
    imageObjects: ["puquio openings", "dry hills"],
    prohibitedVisualElements: ["alien theories", "walking on geoglyphs", "fantasy maps with fake labels"],
  },
  {
    id: "pe-wari",
    countryStream: "peru",
    subject: "Wari civilisation",
    subjectType: "civilisation",
    region: "Ayacucho highlands and Andean expansion zones",
    shortSummary:
      "The Wari civilisation was an influential Andean state centred in the Ayacucho region.",
    verifiedFacts: [
      "Andean civilisation centred near Ayacucho with regional administrative centres.",
      "Known for planned settlements and expansive road-linked networks.",
      "Preceded later Inca state organisation in several highland zones.",
    ],
    modernSignificance:
      "Wari sites help explain long Andean histories of statecraft and highland living.",
    keywords: ["Wari", "Ayacucho"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Culture", "#Wari"],
    sourceReferences: [],
    confidence: "medium",
    reviewStatus: "approved",
    imageBehaviourSignal: "highland path travel between stone settlements",
    imageEnvironment: "Ayacucho highland plateau",
    imageObjects: ["stone architecture at distance", "mountain paths"],
    prohibitedVisualElements: ["fantasy empire collage", "mixed cultures"],
  },
  {
    id: "pe-chimu",
    countryStream: "peru",
    subject: "Chimú civilisation",
    subjectType: "civilisation",
    region: "North coast — Chan Chan region",
    shortSummary:
      "The Chimú civilisation of Peru’s north coast built Chan Chan, a vast adobe urban centre.",
    verifiedFacts: [
      "North-coast civilisation that built Chan Chan, a major adobe city.",
      "Economy included irrigation agriculture, fishing and specialised crafts.",
      "Later incorporated into the expanding Inca state.",
    ],
    modernSignificance:
      "Chimú adobe cities remain key heritage landscapes on Peru’s north coast.",
    keywords: ["Chimú", "Chan Chan"],
    suggestedHashtags: ["#OnlyRealOnesKnow", "#Culture", "#Chimu"],
    sourceReferences: [],
    confidence: "high",
    reviewStatus: "approved",
    imageBehaviourSignal: "coastal craft work and adobe city pathways",
    imageEnvironment: "Chan Chan adobe urban landscape",
    imageObjects: ["adobe walls", "coastal desert light"],
    prohibitedVisualElements: ["treasure-hunt fantasy", "fake gold interiors"],
  },
];

function listApprovedByCountry(countryStreamId) {
  return CULTURAL_CATALOGUE.filter(
    (e) => e.countryStream === countryStreamId && e.reviewStatus === "approved"
  );
}

function getEntryById(id) {
  return CULTURAL_CATALOGUE.find((e) => e.id === id) || null;
}

module.exports = {
  CULTURAL_CATALOGUE,
  listApprovedByCountry,
  getEntryById,
};
